[package]
name = "esp32-hello"
version = "0.1.0"
edition = "2018"

[dependencies]
esp-idf-sys = { path = "../esp-idf-sys" }
esp32-hal = { path = "../esp32-hal" }
embedded-hal = "0.2"
bitflags = "1"
libc = "*"
httparse = "*"
executor = { version = "0.5", default-features = false }
